### ISSUE TITLE
Wasteful CSS

### ISSUE THREAD

**Issue by AbleLincoln** [mikos78/prj-rev-bwfs-dasmoto#5]
You see how you've written the same font-family, font-size, font-weight, and color three separate times? This is a waste of space. You could write all of these styles at once and make them apply to all three of the headings, that is the beauty of CSS. Check it out:
```css
.img1, .img2, .img3 {
    font-family: Helvetica;
    font-size:32px;
    font-weight: bold;
    color:white;
}
```

https://github.com/mikos78/prj-rev-bwfs-dasmoto/blob/master/public_html/index.css#L11-L17
https://github.com/mikos78/prj-rev-bwfs-dasmoto/blob/master/public_html/index.css#L25-L39
